string = "Anderson is a beautiful man"
#string [5:10:2]                     (Intervalo com o espaçamento)
#len(string)                         (Conta quantos elementos tem)
#string.count('o', 3, 10)            (Conta quantos desse elemento tem nesse intervalo)
#string.find('And')                  (Fala o local onde o trecho pedido inicia)
#string.replace('Anderson', 'Paulo') (Troca os valores)
#string.upper()                      (Coloca tudo em maisuculo)
#string.lower()                      (Coloca tudo em minusculo)
#string.capitalize()                 (Coloca a primeira letra em maiusculo)
#string.title()                      (Coloca a primeira letra de todas as palavras em maisusculo)
#string.strip()                      (Remove os espaços desnecessário no inicio e fim)
#string.rstrip()                     (Retira os espaços da direita, e lstrip, da esquerda)
#string.split()                      (Seprar as palavras da string e cria uma lista)
#''.join(string)                     (Junta uma lista e usa o que estiver nas aspas como separador)
